export default {
    'askDataverseEntityNameLbl': 'Enter the name of the entity in Dataverse that has a proxy table generated.',
    'askProxyGenPathLbl': 'Path to Dataverse proxy generator (altpgen.exe)',
    'badDataverseEntityNameErr': 'Dataverse entity is invalid or was not selected',
    'badMappedToTableErr': 'Table to be mapped is invalid or was not selected',
    'badPackagesPathErr': 'Invalid package cache path specified.',
    'badProxyGenPathErr': 'Invalid or no proxy generator path specified.',
    'baseObjectIdLbl': 'Base Object Id',
    'couldNotReadFileContent': 'Could not read contents of file %s.',
    'couldNotReadFolderContent': 'Problem reading folder %s. Does it have any files?',
    'dataverseEntityNameLbl': 'Dataverse Entity Name (case sensitive)',
    'executablesLbl': 'Executables (*.exe)',
    'mapToBCTableLbl': 'Map To Existing Table',
    'noInfoFromProcessMsg': 'No information received from the child process.',
    'noLbl': 'No',
    'openFileLbl': 'Open file',
    'parameterNotSpecifiedErr': '%s not specified.',
    'proxyTableGeneratedMsg': 'Proxy table generated for entity %s.',
    'proxyTableNotFoundMsg': 'Could not find the proxy table generated for entity %s.',
    'selectMappToTableLbl': 'Choose an existing table in Business Central to map to the entity %s.',
    'unexpectedErrorOccuredMsg': 'An unexpected error occured. Please see further details.',
    'yesLbl': 'Yes',
};